name: ASP.NET Build Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-msbuild@v1
        with:
          dotnet-version: '4.x'

      - name: Build solution
        run: dotnet build —configuration Release